spring:
  application:
    name: eureka-server

server:
  port: 10763

port-one: 10761
port-two: 10762
port-three: 10763

eureka:
  instance:
    hostname: localhost
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:${port-one}/eureka/,http://peer2:${port-two}/eureka/