server:
  port: 8771

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://chenlinghong.club:8761/eureka/
spring:
  application:
    name: eureka-service